apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: 16.2.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
 
  values:
    TZ: America/Chicago

    global:
      stopAll: false    
    
    service:
      dns:
        type: LoadBalancer
        loadBalancerIP: ${BLOCKY_IP}

    k8sgateway:
      domains:
      - domain: "${BASE_DOMAIN}"
        dnsChallenge:
          enabled: false
          domain: dns01.clouddns.com