apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:bfy+nwWDLViXhEB3r1DLTrPpNDYdz6p3Uk+b57Ll8twaB84l+8GhgnL7hTJKq8EVHyWwQHJQny/qGLsdazxz3ds=,iv:idx03GhVnmSJssk6+gAN0q2B4l9ZW9fBeBQmgVdE19Y=,tag:H5PyRaI2ZoMmpHZImf+RTg==,type:comment]
    #ENC[AES256_GCM,data:QafJWBk1ILmScFKm4Lpnod8hM9HchtqKzvuFk9A5YGdPUyGLxoVYepxEdHc=,iv:TO+pYBX43T3tEg3bSQlaDyykunrhHBkP+vGrbjvZJI0=,tag:8BQFsqnIJh8xQ8fDUQ0vpw==,type:comment]
    VIP: ENC[AES256_GCM,data:dZdqZ+o3sT+hNOtPdg==,iv:HcTRmCV8t1msvB9UC4PHZU4UMmBzSN5dT7iok5LpwpU=,tag:6rsKYizzkFfi3Ypykszm4A==,type:str]
    #ENC[AES256_GCM,data:ub4Wx9Vnqxkd9cZX63BASN4RqeGZGSSVLKA=,iv:/KZbTq72P2p9ybZpk/NUAWAJ94lpQ4SfVSNOBKzOG34=,tag:gvKU4PtmSDe5mWdrE2xQoQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:LQrJZYLNYJbp8ZSH/zs=,iv:iLvb4Wtz3YoWDVVnu1/VYAk2YfrttYqkj6iIAvH1ixU=,tag:iNvs5zkC3ePEkREibNeCJQ==,type:str]
    #ENC[AES256_GCM,data:Z/62XMCE5eKhf/yijJmadPG5SIq2rzV9Pw/cHqVOs9fTnA==,iv:7QvTjsSAIJU+n3wfCEMzhmi6NDQZDEMrt1e4uhVUD80=,tag:Ap4Z5vFTv5NOGq6dnqj1NA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:/QQnn3fPhfc/bu52,iv:zqmVJyUPMVBNrWNZMJoldJ2ZWr0QMYJwqXavovp2fpY=,tag:VoD2Zd4Tenu6NnkjfSLmcQ==,type:str]
    #ENC[AES256_GCM,data:13cR50nuB62wzqEOOT0NM8qEikxwyNpc+EXBbYBI0gl9fFLa5MrJXmCi3UAkwF4=,iv:Q3sKl/HKO5tmJJrgl/ONpt9mmol5jTuyv82A0xX9VDQ=,tag:WUJh0sqVFvr4YP9gS7dUzA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:vaow1FzRAbn0mM8DWBkkNEpw+OSBGXuBLRFz,iv:GAvbl7AQ71NH4kpX8WgaEGrCx7jPY0k2Dxee6LKnwM0=,tag:nMo1BQ/YLm2U+jHRWPwvQA==,type:str]
    #ENC[AES256_GCM,data:5d0xJS6ws9s/xlxmF7mkWO1p25u0wEEJclB8xXn3a4hmAfvKkX3TZHlrdql3xBv2+1mdIWGS/ckxG5OywVptCCGxxj9n96U+wpFAxfDG+wc=,iv:MsiMCxUMYZ7uOqk5oNMM3CtKx/rxprceD3DeYhk4bIU=,tag:+f1EOpdTXGLDrWvUYMPdFQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:Ffsbz8mWBEemabHQmA==,iv:lTLQYOjEnblSSnIiMatHwlTdEal9z1AYuivMdA1tof0=,tag:vW5ZE6zW16hARiTITMutTA==,type:str]
    #ENC[AES256_GCM,data:VTq4RUgX5f/molIJvF0L/NG07vMvH/kGpf4aNihkB4NFrs6vgsKUs3ejg2B4nxd2voOqvG6WcNE=,iv:PXGi8Nb2PmmM0rJXsWFkMaBdeglbvzBN3Dgd4o8etQA=,tag:LdhrcsujqNC+uHYcwKsjiw==,type:comment]
    #ENC[AES256_GCM,data:9DS4Gtx4NzBWNUZHSWhGwo8liJ8Kl8fMLg==,iv:ouUytAcaA90c7iOx4N0d+VysMIEkzLqFOEflGox2Phs=,tag:I+B43NhQBL4NCWtr+/4OVQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:f1H2AUuk1wgVvWAVOycF42OO7wHYhkWxKuzrBMjm5QpEubuC3KZmGILNOg==,iv:Ae4vUJcPg1lltOBhJnTdSdCnNzjhqKlgz5VMSp01MC0=,tag:48Jc3e5S86Oq6dUtam1Q0Q==,type:str]
    #ENC[AES256_GCM,data:i/BnM4oI0qNe3xKl+A==,iv:fCTYSET/6B3cbgg++d1Z6s4mouoRtDgkjvMoex3Dlek=,tag:G0w/jkdM/Pqim3464slCGg==,type:comment]
    PODNET: ENC[AES256_GCM,data:eEpWax39CHsDkl+KgA==,iv:0jlkf/s1PCjQEgkeim7/5rAT69yHeOYGtv5569w7iWc=,tag:1cRy2uLHms0NQQ8OZl79gA==,type:str]
    SVCNET: ENC[AES256_GCM,data:2ZpQ8q1yXnaNSdihPQ==,iv:DS4iu02x8r2DlSVjzpJXUASn+fbYd2BTYYpd4x+DDAY=,tag:VPhCEp3w1q8FQzj1AhRUsg==,type:str]
    #ENC[AES256_GCM,data:uElzTscO/1/HFA==,iv:FNn52isQG42pHobtjx9pVccEL5foAaoW5cYk8LN/PRY=,tag:VmtSGrVzz4BEX8Mgg557Ag==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:3GnflCH5cY+mx9AM0w==,iv:cplSSFTk1rEGbbo6d0NgHhzMv3LPxd2K+xftZhYiJQw=,tag:imTpQlL48lzs//9xt2pBhQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:ASM7ZkKCnfwa6TabWw==,iv:ngqoZthuFFkpzWE3rhNTjcTQ+zJq97cG0LodTUxh0o4=,tag:wDTVaDfMNmk/KaRKrxTEXw==,type:str]
    OPENSPEEDTEST_IP: ENC[AES256_GCM,data:lRIJGmmwinoWpzYgwA==,iv:4sInyk2hsnFQmq4qvAub2dLqnspMgnwyvZPSbwCuePo=,tag:yj664fCkVXI31OCZX7XXUw==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:TPUYyguZrS3UQv4X2D0=,iv:uQcK+rxk7ijc6cELOLEq8YOJm0it22mC5zsc9S86b8E=,tag:bkIrWwuLXFCm6q3Xlr+XvA==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:yafbU3LSTUZIZytTAIs=,iv:HCBLgBaPLAFnS3eubd9HXxzXBMKQipusMmV0O8LnsTY=,tag:2LvG+vft56ql/OyWqKTv1A==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:yEjNKb9OYiQl1xPSbg==,iv:+0Bz/QkYbMy1b20GOB0qr65x3I89AUdluw8/sN05qdY=,tag:SMxngCOj+cU6ovXnab8dQw==,type:str]
    HA_IP: ENC[AES256_GCM,data:FWwXcrgaJZads+p3bFQ=,iv:ZoIfFC9dkfCDKkFSI1BLTfbOdPvUA9aJ0NEdCPFudrY=,tag:n2pWh3zmGZXKtpfVv2XtAA==,type:str]
    MC_IP: ENC[AES256_GCM,data:rVytpT6UTtdboQZbczg=,iv:pqzEt8BBYr0wWfztbackaTZrlU5gf/udhCphGChwhzs=,tag:9bcG6JDWSBlgTEjZ980o5g==,type:str]
    WIREGUARD_IP: ENC[AES256_GCM,data:W5kuitXo6Gc7dd/MV3Q=,iv:DCDtng3d1PRkYDvqkS8oHk5q5P4ejCUhQKp7hKueGp4=,tag:fSSvCT5Xtor2G2DjY3Hn1g==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:l9GYlSAjeAge9Ef/jnYy37yWz53KDsBZWteRWuU6lC7YWM3aS5QuQA==,iv:Od64dRx6/kCcRdRsz//zi/6QP5giHSfVFgke3c5mszA=,tag:HoqyN8J00Crk/XrIaeVCyQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:MZYrnTDIM6LNXk7249BKjbd1WGdhjzV/lujDOw6Gqw==,iv:aKK2Ycd38i06keJedsURh7wlVHqeWq8HtGbNEYMqt3M=,tag:rXm8uc2QCniOJPw5U1t/3Q==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:s5D6CVEuWAFHGxBrhQ==,iv:xewV0IAxNvl5pPom6B78JhFg98dA4UQUocyOLm3v9s8=,tag:3385Vsp4tS2ADB1pia8PHw==,type:str]
    MAIL_BASE_DOMAIN_RL: ENC[AES256_GCM,data:0XeytiH1sVRVf1NuaaTshUMjvOU0Ktk=,iv:wAw7zbukmB7E++8FMpEnsSwklN8vx1zltUf/6+SZLbg=,tag:PA8Jj5vH+M45QCbqaJCOXQ==,type:str]
    MAIL_BASE_DOMAIN_GCL: ENC[AES256_GCM,data:JRwX8xNAmyJW56J1TvLzNGkZuVKpPdy8xLc=,iv:5gvYlrlOISJF6AOPPF/3loVYSsLLGUOABZc+BlTbHnQ=,tag:JcmuO5DFiTlip9DI/A2i0g==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:wOM5+g==,iv:ooTUV3Q90ktSpyyVi6mDmhjqgZRd04KGDGCCVdOKW+g=,tag:hDo0uR9aFriwzYyITIYFtg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pv50t44kz49dcq4d7jherusgg8muswdqdzwgve44r7l4neyu4gq9mvxsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbi9lS0JNVE96dWxaemxX
            bDRjd29WeEN2WTdLMUYzQnFKaURlUi8wUXdNCk9oNE45bHVEaHZMUHE2NmVkd0Ix
            RTFyOWpaOStsbEM1ZVZ1cnZ6UXgxV28KLS0tIEF0THAyWCtnL0owZXVncW14Nk5z
            cG03VzVjVGJJdUVvMUlFaDJId0JXbGcK3rL5egPej6NN0N+ZukclQ3r5pNmdKzV0
            /FMj8D5PElSi0hNmgiLMtFTi/0IKrC2h9ledwG4zbGlZVBxU+B0o1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-21T15:27:36Z"
    mac: ENC[AES256_GCM,data:r+yyG09Oj3VbMIrmSeXTsOwGwtfkmZu7CgZU42s8PW2x5sokWezz5hPV007DfLvsYNAQTVyoWzkoryhtxJ5QDOkWHND1HDp7undr6t9IGtNQw7bcWcCSq6bISkf7yIK9wEiOCyeZYVA/Fi+llv5FP1w3NaikF5rj3XRXc2sFtOg=,iv:OyQeGZzwOQFX+/PIGNOWCmjRABwyE5ScX9/QHPKHv4A=,tag:TjEGVvShdZQrysViSHlabw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
