apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:SLpvbSDXVTA4XL8pAqwk8UADnme199TVYLFHx0fgLkviZgQ5J1rj3jZQblRvzcg0xcMOxOIfaMQOaZ7CuK3K8UY=,iv:uuE1JV3+O4D5oRdlmNJ3TL7KXuN8Nspb5NqhiD1Y8bc=,tag:iIe8QWE7qIO++a1lk9qyCw==,type:comment]
    #ENC[AES256_GCM,data:hVVQ6Q2AKnkbUs9lTreFrA1X86i+3fES+aonZuPCws9/fBIiTtlLY7c8ZQA=,iv:F5SFdWbicAmg9oQtzNE/yvfyJr3GRodmor2VWPwojWc=,tag:GG4xHkOqxEqhyQ/+qmxKPQ==,type:comment]
    VIP: ENC[AES256_GCM,data:BPi7PLAuW/KD4iSrlQ==,iv:pwNom+0CU7jhGsfP2t/WpC1+yYZfSLNmYeSZDvegwqY=,tag:lL4DZ42VbjR8VzBVR/i6ew==,type:str]
    #ENC[AES256_GCM,data:wSfsPuClsQ0pwEVTbcLTThNcCXLKtDhav5Q=,iv:zZ2FQm07xyNPJgTJ428qV7zZK/UPHj0Zx9O0VQyCcvo=,tag:JnbMPKrvLrBjRKFLLSopPA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:QJTHkdpZpSZsqQn2J3Y=,iv:hD2f3uPcU4wbHAJCkH3twapfgG8ymbToi/cSTWM1fmg=,tag:WEAwkI3X2N3agpQXBSfQeQ==,type:str]
    #ENC[AES256_GCM,data:taR6j5p0N1Im7Kw0WhT6jGMvqNxaN4y0+V7vQ2R2koIP7w==,iv:3cq3o71b9xQ1Lh/WStA3z8z5XOOS+n1JLbzLmnhZ3o0=,tag:ZgaQKm4hMs82I39qGqtyeA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:QVoV4zvOJr5eDO7z,iv:KfHAolI5VdvgUjawTjLznQ+/cTqEK6IGru+24bKpcBA=,tag:lvpqnjmmzxiDV5I+PmxJxA==,type:str]
    #ENC[AES256_GCM,data:jj+JVLcobGxd9ge5to6jVrCgqYcyaFWRUiB9Ry07EWbuYsp8MY3UanM/+kifjT8=,iv:t88KABrIFInHdxNQXGggGgh3UUPHSkXPCQYsnFxfOeM=,tag:VXw/APdMelOyECZx2Hjh0Q==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:6atJqslmvUyIbUIQZFjud35o4L4v6FZDnscS,iv:yfU9VFxu0tgPHtBmWEbBkY1izSVdZf4+lp98Y/LG90k=,tag:0a2LQf27tRSDRQDzduWP/A==,type:str]
    #ENC[AES256_GCM,data:cnTv7hi7ffLEyelMQKJulGlLbFZuo3JOsL84aVyBOy2FYSBSe5hGZCx0wRDU6oY1l+1Aky2XAMGugc91G+yRHRVR3jBBu5IqIohuGdqwaJA=,iv:j1hGfoo9kadZoZ2Ah3wks1BA2uBYPf8ANwuvrlWHOrc=,tag:01AjD0L/9/RmE8d01Fp3ow==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:jZNcCt31KEwaxwORYA==,iv:/rdhpt7nfYtcGZWQ+KjEe7Z+zWIhHZ342EFcZhb+cCI=,tag:WqwKgeLnybEUEWxg0L835A==,type:str]
    #ENC[AES256_GCM,data:l241SaHJHIJ1trAXVbOGU/TQP4RgjUfunLtF4zJmDUHrDxhLM2pXGVZzVDjS/Hamo16QHrP9aRk=,iv:WunsozhbZ33hrNq5dZQZPp8Zgb79VmkgMdM93gVbC6M=,tag:wW/wA0Os4yTyZECxqPlGjg==,type:comment]
    #ENC[AES256_GCM,data:56wnGBiM+IOQP7rIXoNe5YBTMjKhPz1Cag==,iv:gfT4GHeuKVx4acFjqtSP+AjMZ4UTRoBGmaSEG5srjJw=,tag:UdWkUZAe4X4QIuhscpI9YQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:J5xLCumlSb6wVP6NmZeKVGV973SCY0e3tuPy5JtAr6slnx0QR9LWHM1nCw==,iv:bYRnHG2Qvl9CQNcELZEp9tnot8qsuupxECuXDyau5mY=,tag:Ec2+AyzMJ47DiOWAgAj+qw==,type:str]
    #ENC[AES256_GCM,data:vUrHIvENLYOpFTtqlQ==,iv:j8tNlHM5MP9PIzzlTia+Yf8l4T7DDt2pNgJ6NTc5Z2Q=,tag:25NvjWQkBG+HmUrbJfo2TA==,type:comment]
    PODNET: ENC[AES256_GCM,data:TvJibWyaJYWUAqhz9Q==,iv:w93/deGNODFkOmpvbDYnh7qrjCXJFNnB9+crejakTBU=,tag:QNdeZwDFwG6lAxnrsXOg/Q==,type:str]
    SVCNET: ENC[AES256_GCM,data:K/AxeZKUUZQX3Q66/g==,iv:kC0/aBnyfLfEeTs0gkySeSduUV0pCf68JHZ6cWZqBpc=,tag:HNaf+sErXA6WlBvU9sYQuw==,type:str]
    #ENC[AES256_GCM,data:DjmT72cKRYRqUw==,iv:eZBZkJBCHycP9A3gbfilYuBbl5rWB+c65Oe3AbdAFWw=,tag:AGeT8hELb8q3tScYGQzR5Q==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:gu8hrjVe4wEmZ8x/Qw==,iv:Epzu0KvqRDbY8u56mooZ9RzpngIT3nERNP70KGrpa0A=,tag:5kHcEnGTxxbsB1kFCVKIvg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:NieTb6leMDNzFKklPg==,iv:Jn8sIinwMAZZn6UAweIPAQ05gpWUFiFccdl0wK6RcOY=,tag:11nfLeDwUdKN3fNc1JyXdg==,type:str]
    OPENSPEEDTEST_IP: ENC[AES256_GCM,data:VsnmyIQ6huGIxDz38w==,iv:OVJNkr2d5VNQT0jJAf5piazvX/tfuc7NKeoe8TXoZfY=,tag:mbokX7mlQ/R7+IRrpyMElw==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:mxebBdeE1jMCVmivMmA=,iv:0MCtYocd4sJqVf4+7F3ABov7yg76niTSsdekY2cRlyE=,tag:D7+SVpGOvi4Knsrbn+1Iww==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:TGdfUR+OP8YlPbI35io=,iv:jSPjQwunHa8tM4c28HTnNMXjL8TtQ/pFckBCEh3IZP8=,tag:WdeLIchqHus+wgb6fzBhPg==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:akb3EVuZScYIuJgVuEI=,iv:2KcwZ21Ffu9JJVGIj/s10COXTqMovFtkgftKtF6GTP8=,tag:KLx/SB741s9oWUIckdtidw==,type:str]
    HA_IP: ENC[AES256_GCM,data:e7IIH3xeeq0QFpBVJPs=,iv:NfqGwpQT9ONNyP2wRgKfbHTQ35rrF9sZIGzMSKv2NkI=,tag:4Cu253OluW3wSZZCsELRoQ==,type:str]
    MC_IP: ENC[AES256_GCM,data:aKauiBS76hZE+2zIBwY=,iv:rc4/Mx6xedFP+7gv8D1cxNDr2sd0LvzATh77pJChZ7Y=,tag:XVWq5+Qlt1/44lUc2WQbsQ==,type:str]
    WIREGUARD_IP: ENC[AES256_GCM,data:AaFv1OrnFFk+J/+ANHY=,iv:c94weUae/U+6jZQ6b30Yte/SOCKlu9SyNjU3PrgJR6U=,tag:Hh/f4peydltNBy35bVtc2g==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:itFD0j3nBZCrXOprAMEaGy5UMIdhFC3QqjwtvWBWm4MPZaE+7wI/Kg==,iv:JQtJHMou+UZl4/TUie5x4f8oI/mtb8Pa1N+xDHvEbaQ=,tag:TAyVV1odL4jKhDKCSllJyg==,type:str]
    EMAIL: ENC[AES256_GCM,data:qgWcwcpv36Bgq79OvVq8dr3mYdgqwLimYdzoaQgifQ==,iv:K6Y0F9M4rkqf7jq5/I99stGfXJ7z++Px+2cUHYGTq6U=,tag:OdLbsaCP6OExRBPNc7c4kg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:/LkMU/3rcbon0easFA==,iv:ysLrWFnHSMzxzlk3m/OdtOT3zNcTmnxo1zt2ngLl7cM=,tag:Lx7p6o5Ruh7yWyo5r/kUPQ==,type:str]
    MAIL_BASE_DOMAIN_RL: ENC[AES256_GCM,data:vdF/4554BnWeWNxLVzunFdDJkDvBO64=,iv:Kz3iczEHTVEOE8CreqE6Xpuo3gwfAZzj+B2/NWCp7hM=,tag:9Wauzl+JdNyEjujrAwngRA==,type:str]
    MAIL_BASE_DOMAIN_GCL: ENC[AES256_GCM,data:Rjwda+T7xDwlIzxXyW/DHU9ghqxAG6i9XMQ=,iv:pAnbBcaM8dRBPZPpwrH0aJ0RrAADDJgWZVf7+hG/lqw=,tag:Y0Wq2oJeHvZTwCrPBrDIXQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:MrWTdg==,iv:pyfGdbLGY74JDBsMWkmKbOrV7WYBDolQlGMWZXMc8Vk=,tag:IQbXqAKqeacxC4hfNG8fEg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pv50t44kz49dcq4d7jherusgg8muswdqdzwgve44r7l4neyu4gq9mvxsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMWJSUkNIVE41emZpM29X
            N2EwRnc3dWthVmRFblUvTkw0QW9qck5uZmhZCk5aM2N3VWxmMU12anpYVWgyQkty
            Vy9uSVRCaVkrK0M2d1U4eHk1b3o1amsKLS0tIHBrMVJTSjk2Y21IZGpOZERHR2RR
            MHhSY0xBbXB1Y3dRWjhEQ05tYkFxNkUKKOykvtx+5wgypMNcQpemvQUlBABpWItd
            khONlCCUEjR2W7Ry69RzDVbpOgpvtMnHGFJmVylwEuyNp+dgJ8h7Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-21T14:11:47Z"
    mac: ENC[AES256_GCM,data:KZ9mcY6vQ9eLfFEjqbraLf27pSoMm22E4DSXXNdZHfN3GRvK4igzQXea3vsi8g+X/BHrzDvLhjQ4XarVWfz2W+oRRoJ6K6TaTabo20LZk4VtOxHRR07J4MseCzsPfjWeZmQqJ1+AC8Re+vDbAsMPMwqw+0HNr0G4BnE7B45gqW8=,iv:ids9TfFf7E/JiAi/CyCtAb2EA4DfNo833W/zVFn1ONQ=,tag:ohgmB2OGVLZygPbu+ZNF7w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
