apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:axjYUzvhHKvoVOFX8oLrM7gdhXuCCtF8aIJozpQovb9z9KQynGR8nG9XDL1iDu4JsAyEjr18FFGHM8Rxy8VQWomoEQ6f3C+0+uOhj+dv0IZKPbDoFFDmlcFFjUbi0jOxBJi6qmeS0+ndBaLRG7slwr1ERByQWgXy7mmdJkHO8lTqVzLEseHDICKHI4Q0VdSWBtgQvva9RgujadhFEsPdxnrygYrux1CbyqzHe5URBt6EcMdsjhB4jTZIiuvp2O97q3pi2zJVTlXGt8nraLI7+FwugIgB2c/sJGaErtiLf1fMKdz/S59KXKnbcbPvXwglVIAuYwy+WtgSsVglkWnvxD+K+tJTM/hbynNu47C6wTtJjvW4kmfKRkw95FlVE/0v,iv:ZSm3BCAg9tWyfGrbpQwPBYANx7xAzlVsitQeoL0UciE=,tag:1cW4RiVVxA87GmNAAtIDeg==,type:str]
    identity.pub: ENC[AES256_GCM,data:y0e/qFvCOypAHhqAqEYSqV0SPbKXDODF4f2D7Zk6nSl3zq1jpc/s8ApS2OibXlB2N2XkjSz5jwuVbdpaX8tnpAjZBWGO7REBZ42qv4L2+jYB8aGvNgSmzIPjn0aLJoLHJspPCd7aXLwnSe7MyVI3HactKO47WLABJUgDRt0Kh1MBoFSfVHNVUc9XW96tAPcegg6QVBQ3srvgS71BCcmE5XGE24GXaCN/haP7pYg+kJX3gxKQgtGvx3YmK3OF+AopR67oILR2MBenfoO3jQ==,iv:vmHT1oTp13jG9qOIwtIzkzTxyYf6Zniqkw/DBYBrjaU=,tag:KoRooE8tumC51RYWnZ9u/A==,type:str]
    known_hosts: ENC[AES256_GCM,data:vzTY0ZYeMuweyrFMGol355BBo9f8ehf9Z7GyaiuxuvvVaxuOJp1u3Vgi9SZukp0NAZRs4mi6pdxmBM8y76twuRhuv4S2dCi2n6y8SJs3DRFhfp8CYDXFUp1NUbXfXFvJ73zg+isRM/BWh2t87z9VtTP4nFIarTbgUKkKHzuld2NnlKgzroHFsps80oKnTBRyoIHhX7h+BgZ49obnjQqMr/MKf4nx+9ezesnb,iv:YyqQn/AVvzzftKIl7JuEdKs6p4j6FY2xcJSO+ozoaT8=,tag:ECGTJ3QLzsQk8S681WiTeg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pv50t44kz49dcq4d7jherusgg8muswdqdzwgve44r7l4neyu4gq9mvxsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbnNoUVNkVmlqa3VnUVQy
            Y1lkVFJWOHRJYmRvc0szdnRpeFQ4cjB0VUZVCm5IWGNYTkxuT3htUGN6dEowbEx5
            ZHdXaktTZ1J0KzllQnk5NUlmeWo1dnMKLS0tIHRiV2pFQkNoTzdrcWd6emZRU2pa
            aFJHaXhJaC8wNDhTYUl2S242eVFURUUK/oUqN9Hx8enSOk7bKGrs18IAm99nR3Pm
            y6sJm8L4wh5X9iFaiwM+ORnjjPhHPVv2z+AcKftDZHNBit0Uev8hvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-21T15:22:13Z"
    mac: ENC[AES256_GCM,data:IWxq/bB5Ru8feQch6JxQz3C05cOkN/qmurjHK9CgH8+u1gM/r/OCn6XI9h7OgGGSKaa89MNfwMLvTRKXYjBoUkDKgu/95r7OY+zhL61aSCKioeRUisjdpKTw6qj0ZoRD8Y79OMW5HE6olGnACLRt9/c7+ODwFdSPepME3nwPK2k=,iv:c9gnlz/i9L1YQwtD0Zo5qYJ5d9pMFckfhty3+At+XBg=,tag:Ui6FxozMDboCvXVR+Zdx8g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
