---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clusterissuer
  namespace: clusterissuer
spec:
  interval: 15m
  chart:
    spec:
      chart: clusterissuer
      version: 9.1.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Chicago
    clusterIssuer:
      selfSigned:
        enabled: false
      ACME:
      - name: cloudflare
        email: "${EMAIL}"
        server: 'https://acme-v02.api.letsencrypt.org/directory'
        type: cloudflare
        cfapitoken: "${CLOUDFLARE_TOKEN}"